name: flutter_firebase_push_notification
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  get: ^5.0.0-release-candidate-5
  # app_settings: ^5.1.1
  flutter_local_notifications: ^16.3.2
  # firebase_analytics: ^10.8.0
  permission_handler: ^11.2.0
  googleapis_auth: ^1.4.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
